### ISSUE TITLE
[Postman] - Subdomain the Postman setup for the API interaction

### ISSUE THREAD

**Issue by mibuono** [dominant-strategies/quai-postman-collection#1]
Requirements:

Suggest a domain to host the postman docs

**Comment by Juuddi** [comment]
Postman teams account purchased, ready for domain configuration whenever robert has time to get a domain up and verified.

**Comment by Juuddi** [comment]
https://docs.api.qu.ai/

**Comment by Juuddi** [comment]
This issue was moved to jira and completed. Closing as it is no longer relevant here.
